[package]
name = "mqtt-lights"
version = "0.1.0"
authors = ["Tiziano Santoro <tiziano88@gmail.com>"]

[dependencies]
mote = "0.1"
rumqtt = "0.10.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand = "0.5"
rgb = "0.7"
getopts = "0.2"
palette = "0.4"
